spring:
  application:
    name: ib-demo
  profiles:    active:    - dev
    
nexus:  mode: client
  
ib:  container:    plugin:      metrics:
        interval: 60        categories:
          aliveCheck: true
          crashCheck: true
          movable: true
          control: true
          metrics: true          ui: true
