spring:
  application:
    name: ib-demo
  profiles:    active:    - dev
    
nexus:  mode: client
  
ib:
  core:    speed: 1.0
    image-update-frame: 3
  repo:    remote-url: http://localhost:80
  mode:
    story:
      stages:
#      - cn.milai.ibdemo.drama.Hello
      - cn.milai.ibdemo.drama.UnknownVisitor
      - cn.milai.ibdemo.drama.DeepSeaCity
  container:
    plugin:      metrics:
        interval: 60        categories:
          aliveCheck: true
          crashCheck: true
          movable: true
          control: true
          metrics: true          ui: true
